import Head from "next/head";
import { getAuth } from "firebase/auth";
import { Spinner } from "@chakra-ui/react";
import router from "next/router";
import { useAuthState } from "react-firebase-hooks/auth";
import { initFirebase } from "firebaseConfig";

const WelcomeScreen = () => {
  initFirebase();
  const auth = getAuth();
  const [user, loading] = useAuthState(auth);

  if (loading) {
    return <Spinner color="blue.500" />;
  }

  if (!user) {
    // If there is no user, then we must have signed out, so redirect back home
    router.push("/");
    return <Spinner color="red.500" />;
  }

  const signOut = async () => {
    return auth.signOut();
  };

  return (
    <>
      <Head>
        <title>The Clubhouse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <p>Welcome {user?.displayName}</p>
          <button onClick={signOut}>Sign out</button>
        </div>
      </main>
    </>
  );
};

export default WelcomeScreen;
